### ISSUE TITLE
Add support for multiple styles within a single Figma TextNode

### ISSUE THREAD

**Issue by spikelu2016** [bricks-cloud/bricks#26]
**Is your feature request related to a problem? Please describe.**
Currently, Bricks can only support a uniform styling of text within a TextNode. However in Figma, you can apply different styles to different sections of the TextNodes. Therefore, we should add support for having multiple styles within a single Figma TextNode

Styles to support:
- [ ] CSS:
  - [x] fontSize
  - [x] fontName
  - [x] fontWeight
  - [x] textDecoration
  - [x] textCase
  - [ ] ~~lineHeight~~
  - [x] letterSpacing
  - [x] fills
  - [ ] ~~textStyleId~~
  - [ ] ~~fillStyleId~~
  - [x] listOptions
  - [x] indentation
  - [x] hyperlink
- [ ] Tailwind CSS
  - [x] fontSize
  - [x] fontName
  - [x] fontWeight
  - [x] textDecoration
  - [x] textCase
  - [ ] ~~lineHeight~~
  - [x] letterSpacing
  - [x] fills
  - [ ] ~~textStyleId~~
  - [ ] ~~fillStyleId~~
  - [x] listOptions
  - [x] indentation
  - [x] hyperlink

## Default styles map
If there are multiple text styles within a text node, here are the default styles to use for the outermost `<div>`:
- fontSize: `font-size: <the font size with the longest length>;`
- fontName: `font-family: <the font with the longest length>;`
- fontWeight: `font-weight: "normal";` (i.e. Regular font)
- textDecoration: `font-style: "normal";`
- textCase: `text-transform: "none";`
- lineHeight: `line-height: normal;`
- letterSpacing: `letter-spacing: normal;`
- fills: most common blended solid color
- textStyleId: ?
- fillStyleId: ?
- listOptions: ?
- indentation: ?
- hyperlink: ?

Inside the `<div>`, for each different segment of text style, we wrap it in a `<span>` with the overriding styles.

## Todos
1. Modify `getCssAttributes()` in `core/src/design/adapter/figma/adapter.ts` so that it generates default styles if `style === figma.mixed`. For example:
```ts
// font size
if (figmaNode.fontSize !== figma.mixed) {
  attributes["font-size"] = `${figmaNode.fontSize}px`;
} else {
  // add default font size here according to the default styles map above
}
```

2. Modify `getTextProp()` in `core/src/code/generator/html/generator.ts` so that we generate nested `<span>`s for each overriding style.

**Comment by donfour** [comment]
## Update: will pause on mixed line heights for now
The behavior of mixed line height between web and Figma are different. For example, if we have a text with three lines of text:
```
line 1 <-- line height = auto
line 2 <-- line height = 200%
line 3 <-- line height = auto
```
It will look like this in Figma, where the extra space is put above the text:
<img width="161" alt="Screen Shot 2023-05-09 at 10 55 25 AM" src="https://github.com/bricks-cloud/bricks/assets/19992630/2050e045-11cf-4969-afa6-aa73fc4c102e">

And it will look like this in web, where the extra space is distributed equally above and below the text:
<img width="121" alt="Screen Shot 2023-05-09 at 10 56 43 AM" src="https://github.com/bricks-cloud/bricks/assets/19992630/d3808098-0ab5-49ac-96bc-857d62809ff2">

[Link to example Figma file that shows this behavior](https://www.figma.com/file/x3nsK8qfk9SOojmAcXrS36/Line-height-demo?type=design&node-id=0%3A1&t=Ntu7Xr8ECIWIdxvn-1)

Will need more time to think about how to implement.

**Comment by donfour** [comment]
Pausing on implementing mixed `textStyleId` and `fillStlyeId`, as those haven't been implemented yet.

Created https://github.com/bricks-cloud/bricks/issues/77 and https://github.com/bricks-cloud/bricks/issues/76 for `textStyleId` and `fillStlyeId` respectively.
